dbt_postgres:
  outputs:

    dev:
      type: postgres
      threads: 1
      host: localhost
      port: 3310
      user: "{{ env_var('DBT_USER_POST') }}"
      pass: "{{ env_var('DBT_PASSWORD_POST') }}"
      dbname: viidb
      schema: public

    prod:
      type: postgres
      threads: 1
      host: localhost
      port: 3310
      user: "{{ env_var('DBT_USER_POST') }}"
      pass: "{{ env_var('DBT_PASSWORD_POST') }}"
      dbname: viidb
      schema: public

  target: dev
